### ISSUE TITLE
Sequelize model bathroomReview is crashing

### ISSUE THREAD

**Issue by reptile18** [alexastef/loo#42]

**Comment by reptile18** [comment]
C:\Users\repti\OneDrive\Documents\PREWORK_JCL\Homework\loo\node_modules\sequelize\lib\associations\mixin.js:93
      throw new Error(`${source.name}.${_.lowerFirst(Type.name)} called with something that's not a subclass of Sequelize.Model`);
      ^

Error: bathroom_review.belongsTo called with something that's not a subclass of Sequelize.Model
    at Function.<anonymous> (C:\Users\repti\OneDrive\Documents\PREWORK_JCL\Homework\loo\node_modules\sequelize\lib\associations\mixin.js:93:13)
    at Function.bathroomReview.associate (C:\Users\repti\OneDrive\Documents\PREWORK_JCL\Homework\loo\models\bathroomReview.js:7:24)
    at C:\Users\repti\OneDrive\Documents\PREWORK_JCL\Homework\loo\models\index.js:30:19
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (C:\Users\repti\OneDrive\Documents\PREWORK_JCL\Homework\loo\models\index.js:28:17)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1103:10)
    at Module.load (internal/modules/cjs/loader.js:914:32)
    at Function.Module._load (internal/modules/cjs/loader.js:822:14)
    at Module.require (internal/modules/cjs/loader.js:956:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (C:\Users\repti\OneDrive\Documents\PREWORK_JCL\Homework\loo\config\passport.js:4:10)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1103:10)
    at Module.load (internal/modules/cjs/loader.js:914:32)
    at Function.Module._load (internal/modules/cjs/loader.js:822:14)
    at Module.require (internal/modules/cjs/loader.js:956:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (C:\Users\repti\OneDrive\Documents\PREWORK_JCL\Homework\loo\server.js:4:16)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1103:10)
    at Module.load (internal/modules/cjs/loader.js:914:32)
[nodemon] app crashed - waiting for file changes before starting...
[nodemon] restarting due to changes...
[nodemon] starting `node server.js`
[nodemon] restarting due to changes...
[nodemon] starting `node server.js`
C:\Users\repti\OneDrive\Documents\PREWORK_JCL\Homework\loo\node_modules\sequelize\lib\associations\mixin.js:93
      throw new Error(`${source.name}.${_.lowerFirst(Type.name)} called with something that's not a subclass of Sequelize.Model`);
      ^

Error: bathroom_review.belongsTo called with something that's not a subclass of Sequelize.Model
    at Function.<anonymous> (C:\Users\repti\OneDrive\Documents\PREWORK_JCL\Homework\loo\node_modules\sequelize\lib\associations\mixin.js:93:13)
    at Function.bathroomReview.associate (C:\Users\repti\OneDrive\Documents\PREWORK_JCL\Homework\loo\models\bathroomReview.js:7:24)
    at C:\Users\repti\OneDrive\Documents\PREWORK_JCL\Homework\loo\models\index.js:30:19
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (C:\Users\repti\OneDrive\Documents\PREWORK_JCL\Homework\loo\models\index.js:28:17)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1103:10)
    at Module.load (internal/modules/cjs/loader.js:914:32)
    at Function.Module._load (internal/modules/cjs/loader.js:822:14)
    at Module.require (internal/modules/cjs/loader.js:956:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (C:\Users\repti\OneDrive\Documents\PREWORK_JCL\Homework\loo\config\passport.js:4:10)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1103:10)
    at Module.load (internal/modules/cjs/loader.js:914:32)
    at Function.Module._load (internal/modules/cjs/loader.js:822:14)
    at Module.require (internal/modules/cjs/loader.js:956:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (C:\Users\repti\OneDrive\Documents\PREWORK_JCL\Homework\loo\server.js:4:16)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1103:10)
    at Module.load (internal/modules/cjs/loader.js:914:32)
[nodemon] app crashed - waiting for file changes before starting...
[nodemon] restarting due to changes...
[nodemon] starting `node server.js`
[nodemon] restarting due to changes...
[nodemon] restarting due to changes...
[nodemon] starting `node server.js`
C:\Users\repti\OneDrive\Documents\PREWORK_JCL\Homework\loo\node_modules\sequelize\lib\associations\mixin.js:93
      throw new Error(`${source.name}.${_.lowerFirst(Type.name)} called with something that's not a subclass of Sequelize.Model`);
      ^

Error: bathroom_review.belongsTo called with something that's not a subclass of Sequelize.Model
    at Function.<anonymous> (C:\Users\repti\OneDrive\Documents\PREWORK_JCL\Homework\loo\node_modules\sequelize\lib\associations\mixin.js:93:13)
    at Function.bathroomReview.associate (C:\Users\repti\OneDrive\Documents\PREWORK_JCL\Homework\loo\models\bathroomReview.js:7:24)
    at C:\Users\repti\OneDrive\Documents\PREWORK_JCL\Homework\loo\models\index.js:30:19
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (C:\Users\repti\OneDrive\Documents\PREWORK_JCL\Homework\loo\models\index.js:28:17)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1103:10)
    at Module.load (internal/modules/cjs/loader.js:914:32)
    at Function.Module._load (internal/modules/cjs/loader.js:822:14)
    at Module.require (internal/modules/cjs/loader.js:956:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (C:\Users\repti\OneDrive\Documents\PREWORK_JCL\Homework\loo\config\passport.js:4:10)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1103:10)
    at Module.load (internal/modules/cjs/loader.js:914:32)
    at Function.Module._load (internal/modules/cjs/loader.js:822:14)
    at Module.require (internal/modules/cjs/loader.js:956:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (C:\Users\repti\OneDrive\Documents\PREWORK_JCL\Homework\loo\server.js:4:16)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1103:10)
    at Module.load (internal/modules/cjs/loader.js:914:32)
[nodemon] app crashed - waiting for file changes before starting...
